### ISSUE TITLE
Won't install with WooCommerce 3.9.2

### ISSUE THREAD

**Issue by millionleaves** [norcross/woo-better-reviews#14]
I've downloaded v3.0 and get this when I try to activate the plugin:

```
PHP Fatal error:  Uncaught Error: Call to undefined function LiquidWeb\WooBetterReviews\Activate\Helpers\maybe_woo_activated() in /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-content/plugins/woo-better-reviews/includes/activate.php:25
Stack trace:
#0 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-includes/class-wp-hook.php(288): LiquidWeb\WooBetterReviews\Activate\activate()
#1 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters()
#2 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-includes/plugin.php(478): WP_Hook->do_action()
#3 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-admin/includes/plugin.php(681): do_action()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(323): activate_plugin()
#5 [internal function]: Plugin_Command->activate()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#7 [internal function]: WP_C in /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-content/plugins/woo-better-reviews/includes/activate.php on line 25
Fatal error: Uncaught Error: Call to undefined function LiquidWeb\WooBetterReviews\Activate\Helpers\maybe_woo_activated() in /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-content/plugins/woo-better-reviews/includes/activate.php:25
Stack trace:
#0 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-includes/class-wp-hook.php(288): LiquidWeb\WooBetterReviews\Activate\activate()
#1 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters()
#2 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-includes/plugin.php(478): WP_Hook->do_action()
#3 /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-admin/includes/plugin.php(681): do_action()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(323): activate_plugin()
#5 [internal function]: Plugin_Command->activate()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#7 [internal function]: WP_C in /var/www/html/wordpress/demostore.thinkoutside.demo/public/wp-content/plugins/woo-better-reviews/includes/activate.php on line 25
```

**Comment by bswatson** [comment]
Hi @millionleaves,

Thank you for reporting this issue. I've attempted to duplicate it locally and have not been able to do so.

Would you be able to provide additional information, including details on your WordPress and WooCommerce environment to help identify and track down the cause?

Thanks!

**Comment by lukecav** [comment]
Not able to replicate running the current RC of WordPress 5.4 and WooCommerce 4.0.0 RC2
### wp-core ###

version: 5.4-RC1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /chroot/home/a80f149d/no-install.com/html
wordpress_size: 43.32 MB (45421645 bytes)
uploads_path: /chroot/home/a80f149d/no-install.com/html/wp-content/uploads
uploads_size: 3.05 MB (3203356 bytes)
themes_path: /chroot/home/a80f149d/no-install.com/html/wp-content/themes
themes_size: 8.20 MB (8601740 bytes)
plugins_path: /chroot/home/a80f149d/no-install.com/html/wp-content/plugins
plugins_size: 99.17 MB (103982491 bytes)
database_size: 5.20 MB (5455872 bytes)
total_size: 158.94 MB (166665104 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Astra (astra)
version: 2.3.2
author: Brainstorm Force
author_website: https://wpastra.com/about/
parent_theme: none
theme_features: astra_hooks, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, amp, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets, menus
theme_path: /chroot/home/a80f149d/no-install.com/html/wp-content/themes/astra

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Twenty: version: 1.1, author: the WordPress team

### wp-mu-plugins (1) ###

Nexcess Managed Apps: version: 1.6.0, author: Nexcess

### wp-plugins-active (8) ###

Astra Pro: version: 2.3.2, author: Brainstorm Force
Better Reviews For WooCommerce: version: 0.3.0, author: Liquid Web
Cache Enabler: version: 1.3.4, author: KeyCDN
Disable Emails: version: 1.6.1, author: WebAware
Log Emails: version: 1.3.1, author: WebAware
Widget Disable: version: 2.0.0, author: required
WooCommerce: version: 4.0.0-rc.2, author: Automattic
WooCommerce Beta Tester: version: 2.0.1, author: WooCommerce

### wp-plugins-inactive (5) ###

Classic Editor: version: 1.5, author: WordPress Contributors
Core Sitemaps: version: 0.1.0, author: Core Sitemaps Plugin Contributors
Jetpack by WordPress.com: version: 8.3, author: Automattic
WordPress Autoupdates: version: 0.1.5, author: The WordPress Team
WP Redis: version: 1.0.0, author: Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-40 Q16 x86_64 2019-04-15 https://imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 191 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 191 GB
	imagick::RESOURCETYPE_MEMORY: 96 GB
	imagick::RESOURCETYPE_THREAD: 38
gd_version: 2.2.5
ghostscript_version: 9.07

### wp-server ###

server_architecture: Linux 4.14.106-200.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.3.15 64bit
php_sapi: fpm-fcgi
max_input_variables: 16384
time_limit: 600
memory_limit: 2048M
max_input_time: -1
upload_max_size: 1536M
php_post_max_size: 1536M
curl_version: 7.29.0 NSS/3.44
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.2.25-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /chroot/home/a80f149d/no-install.com/html/wp-content
WP_PLUGIN_DIR: /chroot/home/a80f149d/no-install.com/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 2048M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

**Comment by ifyouwillit** [comment]
no response from original poster and unable to duplicate. closing this issue.
