### ISSUE TITLE
Logged in there was an error with your request error showing after review submission

### ISSUE THREAD

**Issue by lukecav** [norcross/woo-better-reviews#3]
After a test review was submitted on the front-end of a published product
/?wbr-success=0&wbr-error-code=missing-formatting-data#tab-reviews

Using two example reviews from this product on Amazon
https://www.amazon.com/Orca-Tactical-Fleece-Military-Beanie/dp/B07MVTMPCR/

The reviews where showing in pending from
/wp-admin/admin.php?page=woo-better-reviews

**Astra** (1.8.0) is the active theme, only active plugins on the test site
**Better Reviews For WooCommerce** (0.0.1)
**WooCommerce** (3.5.7)

**Comment by lukecav** [comment]
Same issue logged in as a customer, using the develop branch of the plugin on a test site. Review was still created and shows in pending.
/wp-admin/admin.php?page=woo-better-reviews&wbr-review-filter=1&wbr-review-status=pending

**Comment by ifyouwillit** [comment]
this issue should now be fixed. please raise another issue if you encounter it again. @lukecav
