### ISSUE TITLE
There was an error with your request and 1 star

### ISSUE THREAD

**Issue by kevin25** [norcross/woo-better-reviews#9]
I got the error with reviewing the products. Please check this screenshot http://prntscr.com/nazbr8

I rated the 5 stars however it only showed 1 star and no review was shown.

I saw this error on server log:

> 2019/04/12 11:10:34 [error] 18207#18207: *33622 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/better-reviews-for-woocommerce/includes/utilities.php on line 469
PHP message: PHP Warning:  array_count_values(): Can only count STRING and INTEGER values! in /home/domain/public_html/wp-content/plugins/better-reviews-for-woocommerce/includes/display/view-output.php on line 130
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-includes/class-wp-list-util.php on line 163
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-includes/class-wp-list-util.php on line 163
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/better-reviews-for-woocommerce/includes/utilities.php on line 469" while reading response header from upstream, client: 91.207.175.216, server: www.domain.com, request: "GET /product/some-url/?wbr-success=0&wbr-error-code=missing-formatting-data HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "www.domain.com"

**Comment by kevin25** [comment]
Can anyone take a look at this error?

**Comment by ifyouwillit** [comment]
@kevin25 i believe this particular issue should be fixed. please let me know if it's still happening, and if so, how to replicate.
